Repository MetaPhase-Consulting/mock-fsbid, pull requests merged in 2023-10, with the labels that each got.

#402 TM-4846: mock setup for job categories
  seeds/data/job_categories.json
  seeds/data/job_category_edit.json
  seeds/data/job_category_skills.json
  src/routes.js
Labels: size/XL, Approved :heavy_check_mark:

#400 add return for manage post access & bid seasons post calls
  seeds/data/backoffice_return_codes.json
  seeds/data/bid_seasons.json
  seeds/data/manage_bid_seasons.json
  seeds/data/search_post_access_filters.json
  src/routes.js
Labels: size/XXL, Approved :heavy_check_mark:

#408 TM-2493, add combined TOD
  src/services/agendas.js
Labels: size/XS
