Repository MetaPhase-Consulting/mock-fsbid, pull requests merged in 2023-08, with the labels that each got.

#386 TM-4521: hard coding in pay plan values
  src/services/agendas.js
  src/services/employees.js
  src/services/positions.js
Labels: size/XS, Approved :heavy_check_mark:

#390 TM-4894 redacted employee EP
  src/routes.js
  src/services/common.js
Labels: dual merge, size/S

#391 Revert "TM-4894 redacted employee EP"
  src/routes.js
  src/services/common.js
Labels: size/S

#387 TM-4682 backoffice EP
  seeds/data/publishable_positions.json
  src/routes.js
Labels: dual merge, size/XXL
