Repository MetaPhase-Consulting/mock-fsbid, pull requests merged in 2024-02, with the labels that each got.

#432 TM-4819-Add-Mock-Data-Org-Stat
  seeds/data/org_stats.json
  src/routes.js
Labels: size/L, Approved :heavy_check_mark:

#422 TM-5308, TM-5413 Assignment Cycle Management Page
  seeds/data/assignment_cycle_add_returns.json
  seeds/data/assignment_cycle_get.json
  seeds/data/assignment_cycles_get.json
  src/routes.js
Labels: size/XXL, Approved :heavy_check_mark:

#439 Revert "TM-5308, TM-5413 Assignment Cycle Management Page"
  seeds/data/assignment_cycle_add_returns.json
  seeds/data/assignment_cycle_get.json
  seeds/data/assignment_cycles_get.json
  src/routes.js
Labels: size/XXL

#441 TM-4917: Manage EL Positions
  src/routes.js
Labels: WIP, size/XS, Approved :heavy_check_mark:

#420 [TM-4919] Bidding Tool Integration
  src/routes.js
Labels: size/S, Approved :heavy_check_mark:

#437 [TM-4680-5389] Projected Vacancy Integration
  src/routes.js
Labels: do not merge, size/XS, Approved :heavy_check_mark:

#442 Feature/assignment cycles
  src/routes.js
Labels: size/XS

#436 Feature/maintain asg
  src/routes.js
Labels: size/XS, Approved :heavy_check_mark:

#444 add route for post open positions
  src/routes.js
Labels: size/XS, Approved
