Repository MetaPhase-Consulting/mock-fsbid, pull requests merged in 2024-01, with the labels that each got.

#429 add data for create, get, and return for Assignment Cycles
  seeds/data/assignment_cycle_add_returns.json
  seeds/data/assignment_cycle_get.json
  seeds/data/assignment_cycles_get.json
  src/routes.js
Labels: size/L

#423 Add status code
  src/services/agendas.js
Labels: size/XS

#430 TM-4990: Employee Info on Panel Meeting Agendas
  src/services/agendas.js
Labels: dual merge, size/M, Approved :heavy_check_mark:

#431 random data for filters
  src/services/agendas.js
Labels: size/XS
